#
#+TITLE:         The End of Authentication
#+AUTHOR:        hellekin
#+DATE:          Sun May 19 18:56:32 2013
#+OPTIONS:       H:8 num:nil toc:nil f:t tags:nil @:t
#+LANGUAGE:      en
#+STYLE:         <link rel="stylesheet" type="text/css" href="style.css" />

listening to: Within (Daft Punk, Random Access Memories)

* Abstract

  We've been taught to believe that identity is something defined by
  an authority, such as a national State, a so-called "trusted"
  third-party, or a Web service.

  It's time to reset and reboot: identity, and therefore
  authentication, is something that each person can, and has to take
  care for themselves.

* The Cryptographic Path to IDENTical diversITY

  Amidst the smoke screen of global terrorism, and pervasive
  surveillance, the yelling majorities call for the "end of privacy"
  and other "electronic war" rethorical lunacies.  But there's no war
  without a very concrete building in which to prepare it, with humans
  making silly decisions, and taking sorry steps; and the post-privacy
  pundits won't take a picture of my ass without assaulting and raping
  me.

  In the early days of hacking at MIT, closing an office door, like
  setting a password to a computer account, were considered offensive.
  That was before the times of firewalls, walled gardens, and global
  surveillance.  Now, we know that idealism must be protected with
  strong cryptography if we want to preserve what's left of our
  privacy.

** Three Myths About Who We Are

   But who is 'we'? Am I part of it? Are you?

*** Myth #1: I Know Who I Am

    Almost all kids in our civilization were born with a name branded
    on them by their parents, or so they think, baptised by a
    name-giving-authority to save them from some birth defect called
    /original sin/, without a say--despite their cries, and classified
    by a number-giving-authority with a life-long "identity".

    We're so used to that *fact* of our lives, that nobody seems to
    question anymore being branded and reduced to a name, a number, a
    health record, a curriculum, or a job resume.  So much are we
    told, and taught, and repeated, that we are the person whose
    mugface is on our passport, whose name is on our diplomas, whose
    career path make up our resume, that we tend to forget that we're
    a living, thus ever changing organism.

    Then one day, John Doe, a Sales Accountant at Pepper Spray
    Corporation, /gets out of his mind/, slams the door, and drives to
    the mountains where he starts planting seeds and watching the sky.
    /What happened/ to /him/? /He was/ so... Now people talk about
    this guy like if he were dead, albeit he just became alive.

*** Myth #2: You Know Who You Are

    Your local instance of a /govern-mental/ institution,
    people-in-the-know, marketers, your neighbors, and including /your
    boss/, all tend to put you in nifty boxes whereby they can count
    you in a bulk, reduce you to a number, a label, most often
    referred to as "your identity". 

    As you very well know it, people suck; you know: "people"; all the
    others, except *me*.  Well, this arrangement is made for you to
    blend in, to comply, to fit in, to obey, to melt in the awful
    crowd of nobodies.  But of course, you're not /one of them/!
    You're special, elite.  You'll recognize yourself.  You know who
    you are. *blink*

*** Myth #3: We Know Who You Are

    Social Security Number, National ID, RFID, traffic cameras,
    fingerprinting, biometry, behavior recognition, insurance record,
    health record, drug test, police record, financial record,
    purchase record, loyalty card...  Cookies, LSO, recommendations,
    avatar, login. Register. Like it or not, /we know who you are/
    (and much, much better than you do).

    The SSL certificate infrastructure is broken! Illegal phone
    tapping is widespread! Large customers databases get compromised!
    ISPs watch their customers browsing habits! The NSA is recording
    all Internet and phone traffic! That's a pretty grim picture we're
    being told about the current state of the global surveillance
    society.

    Faced with such pervasive surveillance, where walking against the
    crowd is a deviant pattern detected by video cameras, there's a
    single step to abandon to the insisting wave of defeatism, and
    kiss goodbye to privacy.

    Yet, even Eric Schmidt, CEO of Google, who famously said that it
    "wants to know everything about you", concedes that with 48 hours
    of video uploaded to Youtube every minute, there's no way the
    company can do anything before the fact. I like to take this as a
    reference before conceding any stress to the Orwellian propaganda
    that reclaims total control over our lives /for our own safety/.

* I Am My Own Community

  I don't need, nor want any kind of a Big Brother. I want freedom. I
  need friends. I am not a number... I'm a person, from Latin
  /persona/, the mask.


** The Right To Heteronymity

   In our degenerate society, I wear the mask that was granted to me
   at birth, only when I interact with the bureaucracy that made it
   for me, for any reason, but certainly not my freedom, nor anyone
   else's freedom.  Otherwise, I keep moving among personas, forging
   avatars as I create new interactions, merging some to my greater
   self, deflecting others to dead ends as I see fit, as to avoid
   profiling, spying, stalking, judgement, and diversion.

   Who needs to know whether I pray for a god, whether I write poetry,
   what is my sexual practice, or my political preferences? If I want
   to share it with you, I will. You may not even recognize me.

** Identical, Yet Different

   That is not to say that names, or to make things clear--here I can
   use the word: an identity, is something to avoid. It's not. Bearing
   a stable identity is mostly useful.  It allows for others to
   establish a /durable/ link, and build trust in you. It provides a
   /stable/ path to recognition, an /endpoint/ for communication.

   Identity becomes problematic when it's used beyond its scope: for
   example, as a container for your self.  Such examples abound, and
   mostly bring harm, usually /permanent damage/, to the /identified/
   person: an atheist, a Black, a Christian, a diabetic, a dissident,
   an enemy, an infidel, a Jew, a Muslim, a woman, etc.; or to
   society: a criminal, a terrorist, a child, a hero, a politician.

** Cryptographic Identity

   An cryptographic identity is a way to establish /with enough
   certainty/, now and for the duration of our purpose, that /whoever
   that is/, the entity with whom we're interacting with remains the
   same, i.e.: is identical.

   "Enough certainty" depends on the risk both parties are willing to
   take before they can establish contact and proceed with their own
   business. "Whoever that is" pinpoints the important feature of the
   identity requirement for any secure transaction: nobody needs to
   know your name, your gender, nor your birth date, in order to
   fulfill *most* purposes.

   Therefore, we propose that instead of establishing permanent
   identities sanctioned by a third party, we can use instead
   permanent endpoints (ourselves, the people we know and trust,
   mathematics) combined with anytime-revocable-identities,
   one-time-identities, and other forms of unique or idempotent
   instrument--a cryptographic principle, and reputation systems, when
   needed.

   The purpose here is not to cover all use-cases, nor to deny the
   need for edge cases, such as the need for accountability in a
   financial transaction, age verification to comply with some legal
   constraint, or a national security clearance.  The goal is to
   provide individuals with a hassle-free security standard that will
   reinforce their privacy the larger the adoption, with few or no
   side-effects.

* IDENTical diversITY

  The proposed standard is based on existing well-known cryptographic
  principles, designs, and protocols. It leverages the public key
  infrastructure, RSA encryption, Transport Layer Security, OpenPGP,
  Bitcoin, Git, etc.

  Each person bears one or more cryptographic key pairs, each attached
  to a unique, distinct, and unrelated identity.  Any given key can be
  derived, so that the main identity can be infered from it, but
  easily revoked by the owner. Does it sound like OpenPGP? Yes.

  Combine it with TLS, and you have... Monkeysphere! Forget about
  Certificate Authorities, and you obtain... WebID! Now, loop back to
  step one: how do you ensure trust, reputation, and secure
  distribution of keys? That's the hard problem.

  I'd say: let's propagate WebID, build the tools to generalize
  MonkeySphere, and from there we can figure out how to merge in what
  has been learned from Bitcoin, Git, and others.

  What about OAuth? Use an One Time Password derived from a WebID, and
  you're set. Transaction done? Key revoked. Need multiple
  transactions? Generate a different key for each consumer, and for
  each action that the consumer is authorized to make. Only one key is
  needed, with infinite tokens available, all revocable at once.

  What about offline? Stick to RSA.

  Isn't it what everybody has been trying to do? Yes, it certainly is,
  and there's been progress on all fronts! I remember the time, before
  MonkeySphere, when the buzz what that it's impossible to share a key
  between SSH and SSL. Times change. They change faster with a shared
  vision.
