#
#+TITLE:         Yell-Occupy Conspiracy
#+AUTHOR:        hellekin
#+DATE:          Sub Dec 15 19 12:28:09 2013
#+OPTIONS:       H:8 num:nil toc:nil f:t tags:nil @:t
#+LANGUAGE:      en
#+STYLE:         <link rel="stylesheet" type="text/css" href="style.css" />

"It is a principle that shines impartially on the just and unjust that
once you have a point of view all history will back you up." -- Van
Wyck Brooks, America's Coming of Age (New York 1915), p.20

* Introduction

A few days ago a friend sent me the link to an article by Carl Gibson
and Steve Horn [0] "exposing" a renowned Serbian activist as a
Stratfor operative. The article was compelling, and as I like to
verify information, I asked Andy Bichlbaum what he thought about
it. Andy was shocked and produced an emotional response [1] the same
day to denounce "yellow journalism". Confident with his conclusions,
Carl Gibson made a public response the same day, that sparked a few
heinous comments. Recently I took the time of reading it and sent the
following to Andy by email. It was not meant for publication, but Andy
propsed I should publish it, so here it is, and it was not
edited. Please keep that in mind when responding to my email.

* Conspiring Deeply and Attentively

First, the detailed response of the authors [2]: thanks to your
intervention, they felt compelled to provide more information [3], and
that's worth the trouble.  The response looks perfectly sound at first
sight--and without paying attention to the opening question nor any
links-- until that paragraph near the end:

: "Ironically, Andy Bichlbaum is taking the same position on Srdja Popovic 
: as the same people at Stratfor whom he called idiots. But unlike
: Bichlbaum, one of the ex-Stratfor sources acknowledged that our
: reporting was sound after reading the investigation."

So, are they trusting an ex-Stratfor source about shooting red bullets
at another ex-Stratfor source, and taking an oppositional stance as
well, including giving more credit to Stratfor emails than Popovic's
account--JUST TO MAKE THEIR POINT? This illustrates my concern about
this and that other article, i.e., with the position the authors chose
to take: it's very much binary, simplistic, and reductionist.

The opening question: "What’s worse? An activist collaborating with an
intelligence organization labeling Bradley (now Chelsea) Manning a
“shit head soldier” who should be fed “to wild dogs” or staunchly
defending an activist who collaborated with that organization?" is
already outrageous: it implies that "An activist" had access to that
information at the time of his collaboration. And then, what? Building
upon this retroactive feature, defending the activist becomes a woe.
Let me try it: I would hope for any good journalist to be able to
provide a saner rhetoric.

I think the situation is a bit more complex than they, or you, depicted
it, and if you would follow up, you should definitely leave the
emotional part out, that you were played on in this response, and focus
on the complexity of the situation--just so that his accusatory
position falls by itself.

In his book "The Democracy Project" [4], David Graeber mentions Otpor!,
with the following nuanced comment (pp 68-69), which appears to me as
capturing that complexity:

: "It’s impossible for activists to really know what the other side is
: thinking. We can’t even really know exactly who the other side is: who’s
: monitoring us, who if anyone was coordinating international security
: efforts against us. But you can’t help but speculate. And it was
: difficult not to notice that back around 1999, right around the time
: that a loose global network of anti-authoritarian collectives began
: mobilizing to shutdown trade summits from Prague to Cancun using
: surprisingly effective techniques of decentralized direct democracy and
: nonviolent civil disobedience, certain elements in the U.S. security
: apparatus began not only studying the phenomenon, but trying to see if
: they could foster such movements themselves."

If I would produce a mimetic response to Gibson, it would be one of
Conspiracy Theory--or Bushism: either you're with us, or you're against
us.  But really, I thought we were way past that. First, I think that's
very interesting and important to understand the connections between
activism and secret service. It's fundamental as it provides a reading
grid to understand world events beyond the mass-media filter--which
happens to be also mediated by CIA-compliant interests. But focusing on
one person is completely demagogic and sensational: it does not make
things better, it does not explain how the intelligence got involved
with these people, nor why such connections can work at all; it only
polarizes attention on the wrong target, and make the
divide-and-conquer-for-the-advancement-of-a-cough-democratic-society
people happy and safe behind their curtains.

That's probably why you dismissed Stratfor as a "lowest-grade, laziest
intelligence" outfit.

I'm surprised that Gibson took the time to write: "Horn’s series
illustrates how Stratfor divides activists in social movements into
several different camps and how those activists could be divided and
conquered as part of the work it was paid to do on behalf of its
corporate clients." and fails to realized how his piece works in the
same way, by using Stratfor as a pretext to attack Popovic instead of
warning activists about such links. In the world of free software we
have a major U.S.-funded program initiated by Radio Free Asia, whose
objective is to promote democracy and combat censorship in Asia. Guess
what kind of scope that is compared to CIA... So we have that fund Open
Technology, with many prominent hackers, including anarchists, working
there, and funding free software projects against censorship... Guess
what, most of the stuff journalists do use and will use in the coming
years are financed by this money. Should we denounce it and refuse to
use Tor, Mailvelope, Cryptocat, Pond, or Riseup's LEAP because we know
the activists are being funded by stooges money?

Sun Tzu told us the truth "Thus one who is skillful at keeping the enemy
on the move maintains deceitful appearances, according to which the
enemy will act." and "All warfare is based on deception. Hence, when
able to attack, we must seem unable; when using our forces, we must seem
inactive; when we are near, we must make the enemy believe we are far
away; when far away, we must make him believe we are near."

What I see here is a typical case of self-deception by
self-importance. It's researching with the response in hand, and
making the investigation look for the right pieces that fit the
puzzle. Nothing to do with thinking, nor research. Gibson should be
working for The Sun, and not claim to be honest and revolutionary.

** Post-Scriptum

Gibson should watch his OPSEC, for he provided the "redacted email" of
Zoe Alif in [[https://s3.amazonaws.com/s3.documentcloud.org/documents/886110/carl-gibson-extensive-email-exchange-with-andy.pdf][revealing his sources]], which is exactly why WikiLeaks has
been attacked before: they made some people's life hell because of
hasty releases (awaiting upcoming AWP's Wikileaks investigation--or
search through the Cables for "please protect")

* Footnotes

[0] http://www.occupy.com/article/exposed-globally-renowned-activist-collaborated-intelligence-firm-stratfor
[1] http://yeslab.org/yellow
[2] http://www.occupy.com/article/how-defending-private-intelligence-firm-collaborators-screws-grassroots-activists
[3] http://pastebin.com/sgL4vP7Z
[4] http://www.scribd.com/doc/152204755/The-Democracy-Project-David-Graeber
